spring:
  datasource:
    username: ecc_event_management
    password: 94020212
    url: jdbc:mysql://10.0.0.8:3306/aipao98?characterEncoding=utf-8&serverTimezone=GMT%2B8&userSSL=false
    driver‐class‐name: com.mysql.cj.jdbc.Driver
    #type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 100MB
  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath*:/mapper/**/*.xml
  jpa:
    hibernate:
      ddl-auto: update  #更新或创建
    show-sql: true #控制台显示